version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  grafana:
    image: grafana/grafana:latest
    environment:
     - GF_SERVER_ROOT_URL=http://localhost:3000
     - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/usr/share/grafana/data
    ports:
      - "3000:3000"
    links:
      - elasticsearch
      
  kibana:
    image: kibana:latest
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    volumes:
      - kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  cerebro:
    image: yannart/cerebro:latest
    ports:
      - "9000:9000"
    links:
      - elasticsearch

volumes:
  kibana:
  grafana:
  elasticsearch:
